### ISSUE TITLE
Ninja related error during training

### ISSUE THREAD

**Issue by zhouhao-learning** [HRNet/HRNet-Semantic-Segmentation#10]
Hello, I am very happy to see your code, I try to run the training, as you said, execute `python tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml`
And I installed `ninja` using the `pip install ninja` method.
```
Traceback (most recent call last):
  File "/atlas/home/hzhou/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 700, in verify_ninja_availability
    subprocess.check_call('ninja --version'.split(), stdout=devnull)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 27, in <module>
    import models
  File "/scratch2/hzhou/HRNet-Semantic-Segmentation/tools/../lib/models/__init__.py", line 11, in <module>
    import models.seg_hrnet
  File "/scratch2/hzhou/HRNet-Semantic-Segmentation/tools/../lib/models/seg_hrnet.py", line 22, in <module>
    from .sync_bn.inplace_abn.bn import InPlaceABNSync
  File "/scratch2/hzhou/HRNet-Semantic-Segmentation/tools/../lib/models/sync_bn/__init__.py", line 1, in <module>
    from .inplace_abn import bn
  File "/scratch2/hzhou/HRNet-Semantic-Segmentation/tools/../lib/models/sync_bn/inplace_abn/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/scratch2/hzhou/HRNet-Semantic-Segmentation/tools/../lib/models/sync_bn/inplace_abn/bn.py", line 14, in <module>
    from functions import *
  File "/scratch2/hzhou/HRNet-Semantic-Segmentation/lib/models/sync_bn/inplace_abn/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/atlas/home/hzhou/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "/atlas/home/hzhou/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 656, in _jit_compile
    verify_ninja_availability()
  File "/atlas/home/hzhou/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 702, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

```
Is this an installation issue or something else? Can you tell me more? Thank you.

**Comment by sunke123** [comment]
You can try this docker. kesun/pose:pytorch-0.4.1-bn-cudnn-off

**Comment by zhouhao-learning** [comment]
@sunke123 
Ok, thank you for your reply.I put the ninja binary into /usr/sbin and then added the environment variable to solve the ninja problem.

In addition, I want to know, HPNet training is very consuming memory, because when I train, return `Segmentation fault`, what is the problem?

**Comment by sunke123** [comment]
Sorry, I have no idea about that.
I think our networks have less memory cost than most of the popular segmentation models, especially if these models adopt dilated-resnet to be backbone.

**Comment by GuangyanZhang** [comment]
您好，我也遇到过一样的问题，请问哪里找ninja这个文件呢，我找不到这个文件

**Comment by ngunauj** [comment]
@GuangyanZhang `pip install ninja `

**Comment by CabbageWust** [comment]
> @sunke123
> Ok, thank you for your reply.I put the ninja binary into /usr/sbin and then added the environment variable to solve the ninja problem.
> 
> In addition, I want to know, HPNet training is very consuming memory, because when I train, return `Segmentation fault`, what is the problem?

你好，可以说说具体放的哪个文件，怎么添加的环境变量吗

**Comment by ngunauj** [comment]
> @sunke123
> Ok, thank you for your reply.I put the ninja binary into /usr/sbin and then added the environment variable to solve the ninja problem.
> 
> In addition, I want to know, HPNet training is very consuming memory, because when I train, return `Segmentation fault`, what is the problem?

Do you solve the problem of `Segmentation fault`, I meet the same problem

**Comment by ngunauj** [comment]
> @sunke123
> Ok, thank you for your reply.I put the ninja binary into /usr/sbin and then added the environment variable to solve the ninja problem.
> 
> In addition, I want to know, HPNet training is very consuming memory, because when I train, return `Segmentation fault`, what is the problem?

Have you solved the error of Segmentation fault?

**Comment by sunke123** [comment]
I have no idea how to reproduce the error.
I trained the HRNet-W48 on 4 P100, which cost about 12-15G memory on each GPU.
