### ISSUE TITLE
NameError: name '_get_default_group' is not defined

### ISSUE THREAD

**Issue by nothingws** [HRNet/HRNet-Semantic-Segmentation#120]
I encountered this error in training. Does anyone know how to correct it?

**Comment by mucunwuxian** [comment]
Hi.

like this?
```
----------------------------------------------------------------------------------------------------------------------------------
Total Multiply Adds (For Convolution and Linear Layers only): 75.98179006576538 GFLOPs
----------------------------------------------------------------------------------------------------------------------------------
Number of Layers
Conv2d : 307 layers   BatchNorm2d : 306 layers   ReLU : 269 layers   Bottleneck : 4 layers   BasicBlock : 104 layers   HighResolutionModule : 8 layers   
Traceback (most recent call last):
  File "tools/train.py", line 286, in <module>
    main()
  File "tools/train.py", line 200, in main
    model, device_ids=[args.local_rank], output_device=args.local_rank)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 268, in __init__
    self.process_group = _get_default_group()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 267, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/lip/seg_hrnet_w48_473x473_sgd_lr7e-3_wd5e-4_bs_40_epoch150.yaml']' returned non-zero exit status 1.
```

I solved as follows.
#122 (comment)
#94 (comment)

**Comment by nothingws** [comment]
yes,That's what I'm having




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mucunwuxian"<notifications@github.com&gt;; 
发送时间: 2020年4月11日(星期六) 晚上7:48
收件人: "HRNet/HRNet-Semantic-Segmentation"<HRNet-Semantic-Segmentation@noreply.github.com&gt;; 
抄送: "闫皓炜"<956681045@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HRNet/HRNet-Semantic-Segmentation] NameError: name &#39;_get_default_group&#39; is not defined (#120)





 
Hi.
 
like this?
 ---------------------------------------------------------------------------------------------------------------------------------- Total Multiply Adds (For Convolution and Linear Layers only): 75.98179006576538 GFLOPs ---------------------------------------------------------------------------------------------------------------------------------- Number of Layers Conv2d : 307 layers   BatchNorm2d : 306 layers   ReLU : 269 layers   Bottleneck : 4 layers   BasicBlock : 104 layers   HighResolutionModule : 8 layers    Traceback (most recent call last):   File "tools/train.py", line 286, in <module&gt;     main()   File "tools/train.py", line 200, in main     model, device_ids=[args.local_rank], output_device=args.local_rank)   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 268, in __init__     self.process_group = _get_default_group()   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 267, in _get_default_group     raise RuntimeError("Default process group has not been initialized, " RuntimeError: Default process group has not been initialized, please make sure to call init_process_group. Traceback (most recent call last):   File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)   File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code     exec(code, run_globals)   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module&gt;     main()   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main     cmd=cmd) subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/lip/seg_hrnet_w48_473x473_sgd_lr7e-3_wd5e-4_bs_40_epoch150.yaml']' returned non-zero exit status 1.  
I solved as follows.
 #122 (comment)
 #94 (comment)

**Comment by Terry-mine** [comment]
Did you solve this problem in windows10？
