### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by achreff** [HRNet/HRNet-Semantic-Segmentation#147]
File "/tools/../lib/core/function.py", line 217, in test
    image, size, name = batch
ValueError: too many values to unpack (expected 3)

Hello
who successfully ran the program
I have this error when i execute 

if 'test' in config.DATASET.TEST_SET:
        test(config, 
             test_dataset, 
             testloader, 
             model,
             sv_dir=final_output_dir)

**Comment by hsfzxjy** [comment]
Hi @achreff . Which branch and dataset are you working on?

**Comment by achreff** [comment]
Hi

My problem is to test the image not validate for cityscapes it work correctly but the prediction for cocostuff can't work.
![Screenshot from 2020-06-06 11-05-22](https://user-images.githubusercontent.com/15703187/83940646-08318080-a7e6-11ea-96ec-fd9d17b8d878.png)


Have the command please to test an images on cocostuff trained model.

thank you

**Comment by hsfzxjy** [comment]
@achreff Cannot reproduce your problem.

BTW, I notice that the line number in your screenshot does not match current code in `HRNet_OCR` branch. Your `main()` is at L129 of `tools/test.py`, but actually it's at L143. Perhaps you are using a wrong script?

**Comment by achreff** [comment]
Ok what is the command to test a set of images on cocostuff please ?

**Comment by hsfzxjy** [comment]
The command in `README.md` is OK. 

What I mean above is that the Python code you currently use may not be the lastest revision in `HRNet_OCR` branch, since the line numbers could not match.

**Comment by achreff** [comment]
i will delete my code and i will test the new

**Comment by achreff** [comment]
I'am sure your code for validation is correct but for test is not ok for uses 
![image](https://user-images.githubusercontent.com/15703187/83967138-199a8b80-a8bf-11ea-9811-43f743e0864e.png)

you can test any image and you will show the bug

**Comment by luowei0701** [comment]
Have you solved the problem? Thanks

**Comment by zhaoliu5254** [comment]
image, size, name = batch
ValueError: too many values to unpack (expected 3)

Have you solved the problem? Thanks

**Comment by zsy7532** [comment]
i have the same problem, did you solve it?
Traceback (most recent call last):
  File "tools/test.py", line 143, in <module>
    main()
  File "tools/test.py", line 135, in main
    sv_dir=final_output_dir)
  File "/home/zsy/HRNet-Semantic-Segmentation/tools/../lib/core/function.py", line 217, in test
    image, size, name = batch
ValueError: too many values to unpack (expected 3)
