### ISSUE TITLE
RuntimeError: No such file pretrained_models/hrnetv2_w48_imagenet_pretrained.pth

### ISSUE THREAD

**Issue by bberry25** [HRNet/HRNet-Semantic-Segmentation#174]
I tried to train pretrained model with cityscapes dataset and already downloaded pretrained model for training.
But I can't find the place for  pretrained_models//hrnetv2_w48_imagenet_pretrained.pth.
Where is the directory for this issue?

The error code is screened like below:
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 322, in <module>
    main()
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 99, in main
    '.get_seg_model')(config)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 678, in get_seg_model
    model.init_weights(cfg.MODEL.PRETRAINED)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 673, in init_weights
    raise RuntimeError('No such file {}'.format(pretrained))
RuntimeError: No such file pretrained_models/hrnetv2_w48_imagenet_pretrained.pth
Traceback (most recent call last):
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 322, in <module>
    main()
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 99, in main
    '.get_seg_model')(config)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 678, in get_seg_model
    model.init_weights(cfg.MODEL.PRETRAINED)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 673, in init_weights
    raise RuntimeError('No such file {}'.format(pretrained))
RuntimeError: No such file pretrained_models/hrnetv2_w48_imagenet_pretrained.pth
=> init weights from normal distribution
=> init weights from normal distribution
Traceback (most recent call last):
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 322, in <module>
    main()
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 99, in main
    '.get_seg_model')(config)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 678, in get_seg_model
    model.init_weights(cfg.MODEL.PRETRAINED)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 673, in init_weights
    raise RuntimeError('No such file {}'.format(pretrained))
RuntimeError: No such file pretrained_models/hrnetv2_w48_imagenet_pretrained.pth
Traceback (most recent call last):
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 322, in <module>
    main()
  File "/home/uc/PY/HRNetOCR/tools/train.py", line 99, in main
    '.get_seg_model')(config)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 678, in get_seg_model
    model.init_weights(cfg.MODEL.PRETRAINED)
  File "/home/uc/PY/HRNetOCR/tools/../lib/models/seg_hrnet_ocr.py", line 673, in init_weights
    raise RuntimeError('No such file {}'.format(pretrained))
RuntimeError: No such file pretrained_models/hrnetv2_w48_imagenet_pretrained.pth
Traceback (most recent call last):
  File "/home/uc/anaconda3/envs/pt_cu100/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/uc/anaconda3/envs/pt_cu100/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uc/anaconda3/envs/pt_cu100/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/uc/anaconda3/envs/pt_cu100/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/gpuc/anaconda3/envs/pt_cu100/bin/python', '-u', '/home/gpuc/PY/HRNetOCR/tools/train.py', '--local_rank=0', '--cfg', '/home/gpuc/PY/HRNetOCR/experiments/cityscapes/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.

**Comment by Heonjin** [comment]
Read README.md
