### ISSUE TITLE
May I ask, I want to train PASCAL, how should I run? I didn't change anything, but I made a mistake in running, thank you

### ISSUE THREAD

**Issue by andrew-begain** [HRNet/HRNet-Semantic-Segmentation#18]

**Comment by andrew-begain** [comment]
File "/home/data/andrew/HRNet_ori/tools/train.py", line 253, in <module>
    main()
  File "/home/data/andrew/HRNet_ori/tools/train.py", line 233, in main
    config, testloader, model, writer_dict)
  File "/home/data/andrew/HRNet_ori/lib/core/function.py", line 72, in validate
    for _, batch in enumerate(tqdm(testloader)):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1000, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 187, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 187, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 173, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 375 and 427 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMath.cpp:3616

**Comment by GuangyanZhang** [comment]
HI，What are the results of your training PASCAL？The result  Miou I get is 67.23,The train data loss is decreaseing,but The validation  loss set remains the same,I'm very puzzle.

**Comment by andrew-begain** [comment]
@GuangyanZhang thank you  very much ,Did you modify the source code while you were training?and Which data set are you using?

**Comment by GuangyanZhang** [comment]
PASCAL voc 2012
