### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by zhaoliu5254** [HRNet/HRNet-Semantic-Segmentation#190]
Hello, I am using PyTorch1.1+Python3.6, both train and val are fine, but I get an error when I test.py:

=> loading model from /model/........./final_state.pth
......
=> loading aux_head.3.bias from pretrained model

  0% 0/2129 [00:00<?, ?it/s]
  0% 0/2129 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/test.py", line 143, in <module>
    main()
  File "tools/test.py", line 135, in main
    sv_dir=final_output_dir)
  File "/code/HRNetV2-OCR_torch1.1.0/tools/../lib/core/function.py", line 217, in test
    image, size, name = batch
ValueError: too many values to unpack (expected 3)
[DEBUG] EXIT signal received in docker container, exiting ...

**Comment by anna-debug** [comment]
I have the same problem, any suggestions?
