### ISSUE TITLE
python tools/test.py --cfg experiments/lip/seg_hrnet_w48_473x473_sgd_lr7e-3_wd5e-4_bs_40_epoch150.yaml          DATASET.TEST_SET list/lip/testvalList.txt              TEST.MODEL_FILE hrnet_w48_lip_cls20_473x473_pytorch-v11.pth              TEST.FLIP_TEST True           TEST.NUM_SAMPLES 0

### ISSUE THREAD

**Issue by enxi3629** [HRNet/HRNet-Semantic-Segmentation#195]
Traceback (most recent call last):
  File "tools/test.py", line 150, in <module>
    main()
  File "tools/test.py", line 119, in main
    for i,j in testloader:
  File "C:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Anaconda\envs\pytorch\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\HRNet\HRNet-Semantic-Segmentation-HRNet-OCR\tools\..\lib\datasets\lip.py", line 90, in __getitem__
    size = label.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by richenyunqi** [comment]
the same error. Can you help us fix it? @sunke123

**Comment by NikhilChowdary-MCW** [comment]
Hi @enxi3629 and @richenyunqi ,
Usually this error occurs when there is an invalid path to the images that are written in .lst files.

Suppose there are 100 images for training and those path was written in .lst files. If one picture path was written and at that path if the image is not present, that the system will through up this error.

Try to debug it and if you feel there are many images that you cannot check, split the .lst file using python code and try to test for small .lst files, then you will know where's the issue.
