### ISSUE TITLE
train error!

### ISSUE THREAD

**Issue by ghost** [HRNet/HRNet-Semantic-Segmentation#216]
(HRNet-Semantic-Segmentation1) C:\code\HRNet-Semantic-Segmentation\tools>python train.py
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    import torch
  File "E:\anaconda3\envs\HRNet-Semantic-Segmentation1\lib\site-packages\torch\__init__.py", line 79, in <module>
    from torch._C import *
ImportError: DLL load failed: 找不到指定的模块。

**Comment by ghost** [comment]
pytorch 1.1.0 is installed.
