### ISSUE TITLE
nccl error

### ISSUE THREAD

**Issue by nistarlwc** [HRNet/HRNet-Semantic-Segmentation#224]
```
Traceback (most recent call last):
  File "tools/train.py", line 322, in <module>
    main()
  File "tools/train.py", line 287, in main
    trainloader, optimizer, model, writer_dict)
  File "/home/lwc/Documents/HRNet-Semantic-Segmentation/tools/../lib/core/function.py", line 66, in train
    loss.backward()
  File "/home/lwc/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/lwc/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /opt/conda/conda-bld/pytorch_1614378124864/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:155, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
Killing subprocess 9467
Traceback (most recent call last):
  File "/home/lwc/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lwc/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lwc/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/lwc/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/lwc/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lwc/anaconda3/envs/mmlab/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/seg_hrnet_ocr_w48.yaml']' died with <Signals.SIGABRT: 6>.

```

`CUDA_VISIBLE_DEVICES=1 
python -m torch.distributed.launch --nproc_per_node=1 --master_port=29650 
        tools/train.py --cfg experiments/seg_hrnet_ocr_w48.yaml`

**Comment by nistarlwc** [comment]
dataset problem, closed

**Comment by niqbal996** [comment]
For anyone else having this error and cannot seem to figure it out like me, if you are training on your custom dataset with different labels than the CityScapes or any other give dataset, you will have to modify the class ID values in `lib/datasets/cityscapes.py` according to your dataset.  
```
self.label_mapping = {-1: ignore_label, 0: ignore_label,
            1: ignore_label, 2: ignore_label,
            3: ignore_label, 4: ignore_label,
            5: ignore_label, 6: ignore_label,
            7: 0, 8: 1, 9: ignore_label,
            10: ignore_label, 11: 2, 12: 3,
            13: 4, 14: ignore_label, 15: ignore_label,
            16: ignore_label, 17: 5, 18: ignore_label,
            19: 6, 20: 7, 21: 8, 22: 9, 23: 10, 24: 11,
            25: 12, 26: 13, 27: 14, 28: 15,
            29: ignore_label, 30: ignore_label,
            31: 16, 32: 17, 33: 18}
```
to values which are suitable to your dataset. In my case, my labels had values of 128 and 255 as class ids and 0 as background. So i had to change it to something like 
```
self.label_mapping = {0: ignore_label, 128: 1, 255: 2} 
```
and also the class weights accordingly. 
```
self.class_weights = torch.FloatTensor([0.2, 0.918, 0.866]).cuda()
```
