### ISSUE TITLE
How to deal with error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\IEDownLoads\\HRNet-Semantic-Segmentation-pytorch-v1.1\\HRNet-Semantic-Segmentation-pytorch-v1.1\\output\\ cityscapes\\seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484\\seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484_2021-06-04-09-40_train.log'

### ISSUE THREAD

**Issue by Tinyyyyyy** [HRNet/HRNet-Semantic-Segmentation#225]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\distributed\launch.py", line 263, in <module>
    main()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\distributed\launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Anaconda3\\envs\\pytorch\\python.exe', '-u', 'tools/train.py', '--local_rank=0', '--cfg',  #'experiments/cityscapes/seg_hr
net_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.

**Comment by sd-spf** [comment]
Have you solved this problem?
