### ISSUE TITLE
models not defined,how can i fix it

### ISSUE THREAD

**Issue by zzc-ai** [HRNet/HRNet-Semantic-Segmentation#241]
Traceback (most recent call last):
  File "tools/test.py", line 144, in <module>
    main()
  File "tools/test.py", line 67, in main
    module = eval('models.'+config.MODEL.NAME)
  File "<string>", line 1, in <module>
NameError: name 'models' is not defined

**Comment by yuanlinwang** [comment]
I use the method:
in train.py

from lib.models import seg_hrnet_ocr
model = eval(config.MODEL.NAME +
                 '.get_seg_model')(config)
