### ISSUE TITLE
自己数据集的实现

### ISSUE THREAD

**Issue by baomimianbobo** [HRNet/HRNet-Semantic-Segmentation#244]
Hello, I want to use my own data set to implement on this network. I have JPG original drawing and JSON file in my hand. How can I change my data set to adapt to the network training？

**Comment by nianjiuhuiyi** [comment]
I also want to know it ! Thank you so much.

**Comment by AirHighway** [comment]
Long times had gone. Someone can help to solve this problem?

**Comment by baomimianbobo** [comment]
Yes! I've done it.&nbsp;Thank you very much for your attention！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HRNet/HRNet-Semantic-Segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HRNet/HRNet-Semantic-Segmentation] 自己数据集的实现 (Issue #244)





 
Long times had gone. Someone can help to solve this problem?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LAOWU1224** [comment]
Hello, I am now trying to use my own dataset on this network, too. I have the orignal PNGs and the label, could you please tell me how to change them so that I can train them? Thank you very much for your help!

**Comment by shata-wh** [comment]
I made my own data as Cityscapes Dataset format, but my dataset only has 6 classes labeled 0-5. 
I change the "self.label_mapping" in lib/datasets/cityscapes.py:
self.label_mapping = {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
But when I was training, the eval on val is:
[0.         0.00423967 0.35140248 0.         0.         0.        ]

Could you tell me how to fix this problem? Was there anything I forgot to modify?

**Comment by Thehonst** [comment]
Hello,I am using myself dateset on this netowrk,but the code "import models" appears error.what's the reason of this.

**Comment by AlanCSU** [comment]
> I made my own data as Cityscapes Dataset format, but my dataset only has 6 classes labeled 0-5. I change the "self.label_mapping" in lib/datasets/cityscapes.py: self.label_mapping = {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5} But when I was training, the eval on val is: [0. 0.00423967 0.35140248 0. 0. 0. ]
> 
> Could you tell me how to fix this problem? Was there anything I forgot to modify?

i got the same problem....

**Comment by ChineseWTAO** [comment]
Traceback (most recent call last):
File "tools/train.py", line 232, in <module>
main()
File "tools/train.py", line 135, in main
train_dataset = eval('dataset.'+cfg.DATASET.DATASET)(
File "<string>", line 1, in <module>
AttributeError: module 'dataset' has no attribute 'mycoco（自己的数据集)'，请问这个报错怎么解决呀
