### ISSUE TITLE
testing error with ninja

### ISSUE THREAD

**Issue by Ximoi** [HRNet/HRNet-Semantic-Segmentation#57]
Hi, I met an error with ninja:
warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Traceback (most recent call last):
  File "/home/fuyi02/anaconda3/envs/pytorch1.0-py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "/home/fuyi02/anaconda3/envs/pytorch1.0-py36/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred: ...........

My conda environment is HRNet=v1.1  pytorch==1.1 cudatoolkit=10.0 ninja==1.8.2
Can you help me?

**Comment by stuhailiu** [comment]
@Ximoi You need to use a lower version of gcc, it is recommended to use 4.9.0
