### ISSUE TITLE
Problem Importing Module

### ISSUE THREAD

**Issue by luizok** [HRNet/HRNet-Semantic-Segmentation#89]
Guys, I got the following problem when I try to import the module:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1066, in _build_extension_module
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hrnet/lib/models/sync_bn/inplace_abn/functions.py", line 13, in <module>
    "inplace_abn_cpu.cpp",
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 866, in _jit_compile
    with_cuda=with_cuda)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 919, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1079, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'inplace_abn': [1/3] c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/local/lib/python3.6/dist-packages/torch/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.6/dist-packages/torch/include/THC -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
FAILED: inplace_abn_cpu.o 
c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/local/lib/python3.6/dist-packages/torch/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.6/dist-packages/torch/include/THC -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp: In function ‘std::vector<at::Tensor> backward_cpu(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, bool, float)’:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:82:41: error: no matching function for call to ‘empty(at::DeprecatedTypeProperties&, <brace-enclosed initializer list>)’
   auto dweight = at::empty(z.type(), {0});
                                         ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:12:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3975:22: note: candidate: at::Tensor at::empty(c10::IntArrayRef, c10::optional<c10::ArrayRef<at::Dimname> >, const c10::TensorOptions&, c10::optional<c10::MemoryFormat>)
 static inline Tensor empty(IntArrayRef size, c10::optional<DimnameList> names, const TensorOptions & options, c10::optional<MemoryFormat> memory_format) {
                      ^~~~~
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3975:22: note:   no known conversion for argument 1 from ‘at::DeprecatedTypeProperties’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3988:22: note: candidate: at::Tensor at::empty(c10::IntArrayRef, const c10::TensorOptions&, c10::optional<c10::MemoryFormat>)
 static inline Tensor empty(IntArrayRef size, const TensorOptions & options, c10::optional<MemoryFormat> memory_format) {
                      ^~~~~
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3988:22: note:   no known conversion for argument 1 from ‘at::DeprecatedTypeProperties’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:83:39: error: no matching function for call to ‘empty(at::DeprecatedTypeProperties&, <brace-enclosed initializer list>)’
   auto dbias = at::empty(z.type(), {0});
                                       ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:12:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3975:22: note: candidate: at::Tensor at::empty(c10::IntArrayRef, c10::optional<c10::ArrayRef<at::Dimname> >, const c10::TensorOptions&, c10::optional<c10::MemoryFormat>)
 static inline Tensor empty(IntArrayRef size, c10::optional<DimnameList> names, const TensorOptions & options, c10::optional<MemoryFormat> memory_format) {
                      ^~~~~
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3975:22: note:   no known conversion for argument 1 from ‘at::DeprecatedTypeProperties’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3988:22: note: candidate: at::Tensor at::empty(c10::IntArrayRef, const c10::TensorOptions&, c10::optional<c10::MemoryFormat>)
 static inline Tensor empty(IntArrayRef size, const TensorOptions & options, c10::optional<MemoryFormat> memory_format) {
                      ^~~~~
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Functions.h:3988:22: note:   no known conversion for argument 1 from ‘at::DeprecatedTypeProperties’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:89:29: error: could not convert ‘{dx, dweight, dbias}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<at::Tensor>’
   return {dx, dweight, dbias};
                             ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp: In lambda function:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:95:33: warning: ‘T* at::Tensor::data() const [with T = double]’ is deprecated [-Wdeprecated-declarations]
     auto *_z = z.data<scalar_t>();
                                 ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:96:35: warning: ‘T* at::Tensor::data() const [with T = double]’ is deprecated [-Wdeprecated-declarations]
     auto *_dz = dz.data<scalar_t>();
                                   ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp: In lambda function:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:95:33: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
     auto *_z = z.data<scalar_t>();
                                 ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:96:35: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
     auto *_dz = dz.data<scalar_t>();
                                   ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp: In lambda function:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:110:33: warning: ‘T* at::Tensor::data() const [with T = double]’ is deprecated [-Wdeprecated-declarations]
     auto *_z = z.data<scalar_t>();
                                 ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:111:35: warning: ‘T* at::Tensor::data() const [with T = double]’ is deprecated [-Wdeprecated-declarations]
     auto *_dz = dz.data<scalar_t>();
                                   ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp: In lambda function:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:110:33: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
     auto *_z = z.data<scalar_t>();
                                 ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:111:35: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
     auto *_dz = dz.data<scalar_t>();
                                   ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn_cpu.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:322:7: note: declared here
   T * data() const {
       ^~~~
[2/3] c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/local/lib/python3.6/dist-packages/torch/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.6/dist-packages/torch/include/THC -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn.cpp -o inplace_abn.o
FAILED: inplace_abn.o 
c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/local/lib/python3.6/dist-packages/torch/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.6/dist-packages/torch/include/THC -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn.cpp -o inplace_abn.o
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn.cpp: In function ‘void pybind11_init_inplace_abn(pybind11::module&)’:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn.cpp:70:69: error: no matching function for call to ‘pybind11::module::def(const char [9], <unresolved overloaded function type>, const char [36])’
   m.def("backward", &backward, "Second part of backward computation");
                                                                     ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/utils/pybind.h:6:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/python.h:12,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:6,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/torch.h:6,
                 from /content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/pybind11/pybind11.h:810:13: note: candidate: template<class Func, class ... Extra> pybind11::module& pybind11::module::def(const char*, Func&&, const Extra& ...)
     module &def(const char *name_, Func &&f, const Extra& ... extra) {
             ^~~
/usr/local/lib/python3.6/dist-packages/torch/include/pybind11/pybind11.h:810:13: note:   template argument deduction/substitution failed:
/content/hrnet/lib/models/sync_bn/inplace_abn/src/inplace_abn.cpp:70:69: note:   couldn't deduce template parameter ‘Func’
   m.def("backward", &backward, "Second part of backward computation");
                                                                     ^
ninja: build stopped: subcommand failed.
```

Someone had the same problem or know how to solve it? Thanks

**Comment by rxmao** [comment]
you can change to CUDA10.0
